In [1]:
import sys 
sys.path.append("..") 

import numpy as np
import numpy.linalg as LA
from braiding_model import BraidOperator, show_braid_words
from braiding_model import GeneratorBraid, obtain_model_braid, obtain_model_torus_knot
from braiding_model import sigma_z, sigma_x, sigma_y, sigma_0
from braiding_model import PerturbationModel
from braiding_model import obtain_non_Hermitian_Hamiltonian, obtain_non_Hermitian_model

from machine_learning import Classifier, Cluster
from topology import topology_comparator, similarity_function
from functools import partial

import matplotlib.pyplot as plt

p1 = PerturbationModel()
p1.set_parameters(t1=0.1,t2=0.0)

p2 = PerturbationModel()
p2.set_parameters(t1=-0.1,t2=0.0)

p3 = PerturbationModel()
p3.set_parameters(t1=0.1,t2=0.1)

p4 = PerturbationModel()
p4.set_parameters(t1=0.0,t2=-0.1)

perturbations = [p1,p2,p3,p4]

np.seterr(all="ignore") # ignore some numerical errors

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

__Winding matrix__:

    + Gauge dependent: deformation leads to an identical braid but results in a different winding matrix
    + Label dependent: elements change when the labels change

# Unknot

In [2]:
def func(k):
    H = np.array([
        [0, 0, 1j*np.exp(-1j*k)],
        [1, 0, 0],
        [0, 1, 0]
    ])
    return H

n_band = len(func(0))
#hamiltonian = obtain_non_Hermitian_Hamiltonian(n_band=n_band, func=func, compress_ratio=0.75)
model =  obtain_non_Hermitian_model(n_band=n_band, func=func, compress_ratio=0.8)
model.get_winding_matrix()

array([[ 0. , -0.5, -0.5],
       [-0.5,  0. , -0. ],
       [-0.5, -0. ,  0. ]])

In [7]:
braid_operators = [BraidOperator(1), BraidOperator(2)]
model =  obtain_model_braid(n_band, braid_operators)
model.get_winding_matrix()

array([[ 0. , -0.5, -0.5],
       [-0.5,  0. ,  0. ],
       [-0.5,  0. ,  0. ]])

In [48]:
def func(k):
    H = np.array([
        [0, 0, np.exp(-2j*k)],
        [1, 0, 0],
        [0, 1, 0]
    ])
    return H

n_band = len(func(0))
#hamiltonian = obtain_non_Hermitian_Hamiltonian(n_band=n_band, func=func, compress_ratio=0.75)
model =  obtain_non_Hermitian_model(n_band=n_band, func=func, compress_ratio=0.8)
model.get_winding_matrix()

array([[ 0. , -0.5, -0.5],
       [-0.5,  0. , -1. ],
       [-0.5, -1. ,  0. ]])

In [50]:
braid_operators = [BraidOperator(2), BraidOperator(1),BraidOperator(2), BraidOperator(1)]
model =  obtain_model_braid(n_band, braid_operators)
model.get_winding_matrix()

array([[ 0. , -0.5, -0.5],
       [-0.5,  0. , -1. ],
       [-0.5, -1. ,  0. ]])

In [52]:
def func(k):
    H = np.array([
        [0, 0, -np.exp(-1j*k)],
        [1, 0, 0],
        [0, 1, 0]
    ])
    return H

n_band = len(func(0))
#hamiltonian = obtain_non_Hermitian_Hamiltonian(n_band=n_band, func=func, compress_ratio=0.75)
model =  obtain_non_Hermitian_model(n_band=n_band, func=func, compress_ratio=0.8)
model.get_winding_matrix()

array([[ 0. , -0.5, -0.5],
       [-0.5,  0. ,  0. ],
       [-0.5,  0. ,  0. ]])

In [56]:
def func(k):
    H = np.array([
        [0, np.exp(-1j*k), -np.exp(-1j*k)],
        [1, 0, 0],
        [0, 1, 0]
    ])
    return H

n_band = len(func(0))
#hamiltonian = obtain_non_Hermitian_Hamiltonian(n_band=n_band, func=func, compress_ratio=0.75)
model =  obtain_non_Hermitian_model(n_band=n_band, func=func, compress_ratio=1.)
print(model.get_winding_matrix())

model =  obtain_non_Hermitian_model(n_band=n_band, func=func, compress_ratio=0.75)
print(model.get_winding_matrix())

[[ 0.   -0.41 -0.29]
 [-0.41  0.   -0.29]
 [-0.29 -0.29  0.  ]]
[[ 0.  -0.5 -0.5]
 [-0.5  0.  -0. ]
 [-0.5 -0.   0. ]]


In [55]:
def func(k):
    H = np.array([
        [0, np.exp(-2j*k), 0, np.exp(-1j*k)],
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0]
    ])
    return H

n_band = len(func(0))
#hamiltonian = obtain_non_Hermitian_Hamiltonian(n_band=n_band, func=func, compress_ratio=0.75)
model =  obtain_non_Hermitian_model(n_band=n_band, func=func, compress_ratio=1.)
print(model.get_winding_matrix())

model =  obtain_non_Hermitian_model(n_band=n_band, func=func, compress_ratio=0.75)
print(model.get_winding_matrix())

[[ 0.   -0.18 -0.32 -0.25]
 [-0.18  0.   -0.25 -0.32]
 [-0.32 -0.25  0.   -0.18]
 [-0.25 -0.32 -0.18  0.  ]]
[[ 0.  -0.5 -0.  -0.5]
 [-0.5  0.   0.   0. ]
 [-0.   0.   0.  -0.5]
 [-0.5  0.  -0.5  0. ]]


# General

In [32]:
def func(k):
    H = np.array([
        [2, np.exp(2j*k), np.exp(1j*k)],
        [1, 0, 0],
        [0, 1, 0]
    ])
    return H

n_band = len(func(0))
#hamiltonian = obtain_non_Hermitian_Hamiltonian(n_band=n_band, func=func, compress_ratio=0.75)
model =  obtain_non_Hermitian_model(n_band=n_band, func=func, compress_ratio=0.75)
model.get_winding_matrix()

array([[ 0. ,  0.5,  1. ],
       [ 0.5,  0. , -0. ],
       [ 1. , -0. ,  0. ]])

In [34]:
braid_operators = [BraidOperator(-1), BraidOperator(-2), BraidOperator(-2)]
model =  obtain_model_braid(n_band, braid_operators)
model.get_winding_matrix()

array([[0. , 0.5, 1. ],
       [0.5, 0. , 0. ],
       [1. , 0. , 0. ]])

In [35]:
def func(k):
    H = np.array([
        [2, np.exp(2j*k), np.exp(1j*k)],
        [1, 0, 0],
        [0, 1, 0]
    ])
    return H

n_band = len(func(0))
#hamiltonian = obtain_non_Hermitian_Hamiltonian(n_band=n_band, func=func, compress_ratio=0.75)
model =  obtain_non_Hermitian_model(n_band=n_band, func=func, compress_ratio=1.)
model.get_winding_matrix()

array([[0.  , 0.5 , 0.94],
       [0.5 , 0.  , 0.06],
       [0.94, 0.06, 0.  ]])

# Case I

In [38]:
def func(k):
    H = np.array([
        [2, np.exp(2j*k), np.exp(-1j*k)],
        [1, 0, 0],
        [0, 1, 0]
    ])
    return H

n_band = len(func(0))
#hamiltonian = obtain_non_Hermitian_Hamiltonian(n_band=n_band, func=func, compress_ratio=0.75)
model =  obtain_non_Hermitian_model(n_band=n_band, func=func, compress_ratio=1.)
print(model.get_winding_matrix())

model =  obtain_non_Hermitian_model(n_band=n_band, func=func, compress_ratio=0.75)
print(model.get_winding_matrix())

[[ 0.   -0.5  -0.06]
 [-0.5   0.    0.06]
 [-0.06  0.06  0.  ]]
[[ 0.  -0.5  0. ]
 [-0.5  0.   0. ]
 [ 0.   0.   0. ]]


In [40]:
def func(k):
    H = np.array([
        [2, np.exp(-1j*k), np.exp(2j*k)],
        [1, 0, 0],
        [0, 1, 0]
    ])
    return H

n_band = len(func(0))
#hamiltonian = obtain_non_Hermitian_Hamiltonian(n_band=n_band, func=func, compress_ratio=0.75)
model =  obtain_non_Hermitian_model(n_band=n_band, func=func, compress_ratio=1.)
print(model.get_winding_matrix())

model =  obtain_non_Hermitian_model(n_band=n_band, func=func, compress_ratio=0.75)
print(model.get_winding_matrix())

[[ 0.  1.  0.]
 [ 1.  0. -0.]
 [ 0. -0.  0.]]
[[ 0.  1. -0.]
 [ 1.  0.  0.]
 [-0.  0.  0.]]


In [41]:
def func(k):
    H = np.array([
        [0, 0, np.exp(-1j*k)],
        [1, 0, 0],
        [0, 1, 0]
    ])
    return H

n_band = len(func(0))
#hamiltonian = obtain_non_Hermitian_Hamiltonian(n_band=n_band, func=func, compress_ratio=0.75)
model =  obtain_non_Hermitian_model(n_band=n_band, func=func, compress_ratio=1.)
print(model.get_winding_matrix())

model =  obtain_non_Hermitian_model(n_band=n_band, func=func, compress_ratio=0.75)
print(model.get_winding_matrix())

[[ 0.   -0.33 -0.33]
 [-0.33  0.   -0.33]
 [-0.33 -0.33  0.  ]]
[[ 0.  -0.  -0.5]
 [-0.   0.  -0.5]
 [-0.5 -0.5  0. ]]


In [42]:
def func(k):
    H = np.array([
        [2, np.exp(-3j*k), np.exp(1j*k)],
        [1, 0, 0],
        [0, 1, 0]
    ])
    return H

n_band = len(func(0))
#hamiltonian = obtain_non_Hermitian_Hamiltonian(n_band=n_band, func=func, compress_ratio=0.75)
model =  obtain_non_Hermitian_model(n_band=n_band, func=func, compress_ratio=1.)
print(model.get_winding_matrix())

model =  obtain_non_Hermitian_model(n_band=n_band, func=func, compress_ratio=0.75)
print(model.get_winding_matrix())

[[ 0.    0.28 -0.56]
 [ 0.28  0.    0.28]
 [-0.56  0.28  0.  ]]
[[ 0.   0.5 -0.5]
 [ 0.5  0.   0. ]
 [-0.5  0.   0. ]]


# $\sigma_2^{-1} \sigma_1$

In [45]:
braid_operators = [BraidOperator(1), BraidOperator(-2)]
model =  obtain_model_braid(n_band, braid_operators)
model.get_winding_matrix()

array([[ 0. , -0.5,  0.5],
       [-0.5,  0. ,  0. ],
       [ 0.5,  0. ,  0. ]])

In [ ]:
braid_operators = [BraidOperator(1), BraidOperator(-2)]
model =  obtain_model_braid(n_band, braid_operators)
model.get_winding_matrix()